= Robot Hackathon - Team <GUID>
// Refs:
:url-ocpconsole: <OCP_CONSOLE_URL>
:url-codeready: <CRC_CONSOLE_URL>
:url-3scale: <3SCALE_CONSOLE_URL>
:url-gogs: <GOGS_CONSOLE_URL>

== Introduction

Welcome Team <GUID>!

You are a special mission super coder/geek. Your mission is to complete 
several assignements using a state-of-the-art robot in a dangerous environment. 
The robot is provided by Robot Services, Ltd. Because speed is of utmost 
importance you will utilize agile and DevOps based development 
methodologies. To get productive quickly you will use the container 
platform OpenShift which will be provided by Robot Services. 

== Your Adventure starts... connect to the Robot

=== Access the API

Robot Service Ltd provides access to their robots through an API gateway based 
on the 3Scale API Management platform.

TIP: As the robots are accessed over a public API, it's important to 
restrict and limit who can use the API. The API management platform takes care 
of role-based access control, setting up accounts, monitoring, routing, traffic 
shaping and more.

WARNING: Please access all the follwing URLs as a team on one laptop (not individually), as you are now a DevOps 
team and want to be on the same page. Also the cloud system is sized for one account per team performance wise. 

Okay, let's get started. Head over to the {url-3scale}[3Scale web UI^] and:

* Click on `*SIGN IN*` in the upper right
* Login with your team credentials (`*<GUID>*`, password as provided)
* After login you will see the API key you need to access the robot API

TIP: Look around in the 3Scale web UI, you will see examples of how to invoke 
the API of your robot. 3Scale will take care of routing your requests to the 
Hub-Controller which in turn accesses your robot. 

WARNING: The most important information is the *Key* from the *Credentials* 
box. Using this key as parameter *user_key* in your API calls takes care of routing the 
requests to the proper robot. Your *Key* is: `*<GUID>*`

==== Testing the API

The easiest way to test the connection to the Hub-Controller is to use the 
curl commandline example found under the section *Run your requests*. Try this command in you terminal. This will test the connection to the Hub-Controller, *not* the robot!

The commandline to run and the output should resemble this example:
----
curl <3SCALE_URL>/api/robot/status?user_key=<GUID>
OK
----

If you don't have a laptop with the `curl`-command don't worry, you can test this also through the 3Scale webinterface in the next section.

==== Exploring the Robot API

There are a number of ways to test the connectivity from your PC via 3Scale to 
the robot. You basically need to construct an URL to query the API using 
the 3Scale access token.

While in the 3Scale web UI access the *DOCUMENTATION* link in the menu bar. 
Here you will find the REST API documentation of all robot operation currently 
exposed in OpenAPI/Swagger format.

You can test the available API calls from here. These will actually go to your 
robot. Just remember to fill in `*<GUID>*` as `USER_KEY` when you test.

TIP: Why don't you let the little guy drive around for a few cm?

=== Accessing OpenShift

Now that you can access and control your robot through the API let's get 
started with programming the robot by developing applications on our container 
platform. 

Your team user has already been created for you, your user name is `*<GUID>*`. Click {url-ocpconsole}[here^] to access the OpenShift web UI.

* Login as your team user, `*<GUID>*`, the password will be provided
* Accept the self-signed certificate in you browser 
* Look around the OpenShift Console
* If you see the error: `An error occurred getting metrics.` 
** Click on *Open metrics URL* and trust this certificate as well
* Then reload you Browser to see the metrics

=== Your first application

So we are ready to start with some coding. Normally you would now have to setup your 
dev environment on your laptop... install IDE, language runtimes, build tools, version control 
system/access, checkout code.... etc. And most of this would be specific to your OS.

Because we work in a cutting edge environment we'll use CodeReady Workspaces,
a browser-based, cloud-native IDE running in the OpenShift environment.

To access CodeReady in your browser click {url-codeready}[here^]. In the login window click the button *Openshift v3* to use OpenShift authentication. 

Login with `*<GUID>*` as username and the provided password.

CodeReady Workspaces provides development environments for several languages and runtimes. You have the choice between Java, Python and PHP.

==== Launch your workspace from CodeReady

After login you are in the Workspace management view of CodeReady Workspaces. Create your 
workspace and choose `Java`, `Python` or `php` as your programming language, depending on the language that you want to develop you robot application in:

* *NAME*: `<GUID>-robot-app-workspace` 
* *SELECT STACK*: `Java Cloud-Native` / `Python` / `php`
* Click `*CREATE*`
* After creation has finished a pop-up appears, click *OPEN In IDE*.

Now your CodeReady workspace is running as a new Pod in OpenShift and should open in your browser. 

WARNING: Remember to only create one workspace per team. Creating a new workspace can take some time.

==== Setup Your Application Template 

Depending on your programming language choice, please refer to one of the following respective guides on how to set up your application and get started.

===== https://adoc.redhat.partners/lab/build-github.php?guid=<GUID>&file=robot-java-module.adoc&dir=/nexus-Six/openshift-robot-hackathon/master/doc/[Go on with Java^]

===== https://adoc.redhat.partners/lab/build-github.php?guid=<GUID>&file=robot-python-module.adoc&dir=/nexus-Six/openshift-robot-hackathon/master/doc/[Go on with Python^]

===== https://adoc.redhat.partners/lab/build-github.php?guid=<GUID>&file=robot-php-module.adoc&dir=/nexus-Six/openshift-robot-hackathon/master/doc/[Go on with PHP^]

== Now the Fun Starts!

Okay, by now you should have:

* set up a complete Cloud Native Development Environment in the programming language of your choice  
* gone through some training missions to get you up to speed

You have all the information to get started hacking the robot!

=== Final Mission

As explained your mission will be to navigate your robot through an unkown labyrinth with a combination of driving and distance checks. So prepare and test your robot with different maze variations.

Good Luck and Robotz Go, Go, Go! 

== Links

{url-3scale}[3Scale Web UI^]

{url-ocpconsole}[OpenShift Web UI^]

{url-codeready}[CodeReady Workspaces Web UI^]

{url-gogs}[Gogs Web UI^]








